# Generated by Django 5.0 on 2023-12-31 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='marcado_em',
        ),
        migrations.AlterField(
            model_name='todo',
            name='data_consulta',
            field=models.DateField(),
        ),
    ]
