# Generated by Django 5.0 on 2023-12-31 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0002_remove_todo_marcado_em_alter_todo_data_consulta'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='hora_consulta',
            field=models.TimeField(null=True),
        ),
    ]
